#!/bin/bash
echo starting batch job initialization

EL_JOBID=$(printf "%03d" $1)
WHICHFILENUMBER=$(($1 + 1))

# The worker node directory is the working directory
WORKER_DIR=${PWD}
echo -e ${GREEN} Starting from directory ${PWD} ${NC};
# Get a specific file determined by a specific line in the input file.
THEDIR=$2
INPUTLIST=$(ls $THEDIR | grep txt)
INPUTFILE=$(cat $THEDIR/$INPUTLIST | head -n $WHICHFILENUMBER | tail -n 1)

# Set up ATLAS, athena
export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
alias 'setupATLAS=source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh    

# Set up this local version of athena
cd /nfs/dust/atlas/user/brendlik/validation/conversionTuning/source
asetup Athena,master,2021-04-26T2101,64,here
source $TestArea/../build/$Athena_PLATFORM/setup.sh

echo -e ${GREEN} Running Reco_tf.py. ${NC};
cd $WORKER_DIR
echo -e ${GREEN} Running from directory ${PWD} ${NC};

echo THEDIR: $THEDIR
echo WHICHFILENUMBER: $WHICHFILENUMBER
echo INPUTLIST: $INPUTLIST
echo INPUTFILE: $INPUTFILE

Reco_tf.py --inputRDOFile=$INPUTFILE --outputAODFile=Nightly_AOD_gamma.pool.root \
--autoConfiguration="everything" --conditionsTag="$CONDITIONSTAG" \
--preExec="$PREEXEC" --postExec "$POSTEXEC_A" "$POSTEXEC_B"

echo contents of directory below
ls;

# athena -c "particleType='gamma'" $TestArea/../build/$Athena_PLATFORM/jobOptions/egammaValidation/egamma_art_checker_joboptions.py

# Move from the temp space.
# mv /tmp/$USER/$THEDIR/$THEJOBDIR $TestArea/../run/$THEDIR/.

echo done.
echo -e ${GREEN} Finished. ${NC};
